<../../mkconfig

TARG=\
	cryptfile.dis\
	testpbkdf2.dis\

MODULES=\
	../lib/pbkdf2.m\

SYSMODULES=\
	arg.m\
	bufio.m\
	daytime.m\
	draw.m\
	keyring.m\
	string.m\
	sys.m\

DISBIN=$ROOT/dis

<$ROOT/mkfiles/mkdis
